# Hugo Config 
#  port-hugo theme uses: params (plugins, preloader, social, logos, etc.), menu.main
#  Content for the single-page layout comes from data/content.yml (not the content/ dir).

baseURL = "https://example.org/"
languageCode = "en-us"
title = "Portfolio of Lindsey Carriere"
theme = "port-hugo"

### Plugins ###

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


### Navigation ###

# main menu
[[menu.main]]
name = "Home"
url = "#header"
weight = 1

[[menu.main]]
name = "About Lindsey"
url = "#about"
weight = 2

[[menu.main]]
name = "Fun Facts"
url = "#funfacts"
weight = 3

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 4

# [[menu.main]]
# name = "Portfolio"
# url = "#portfolio"
# weight = 5


### Default Params ###

[params]
copyright = "Powered by Hugo | Theme: port-hugo | Lindsey Carriere &copy;"
# Meta data
description = "Portfolio of Lindsey Carriere"
author = "Lindsey Carriere"
favicon = "images/favicon.png"
google_analytics = "G-ABCDEFG123" # TODO: Add Google Analytics
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.


### Social ###

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/lindsey-carriere/"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/lindseycarriere"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:carriere+portfolio@gmail.com"

# [[params.social]]
# icon = "fab fa-medium"
# link = "https://medium.com/@gusburton"
